In [1]:
import numpy as np

In [3]:
a1=np.array([1,2,3])
print(a1.ndim)#查看数组维数

1


In [8]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2.ndim)

2


In [18]:
#三维数组
a3=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

3


In [12]:
print(a1.shape)#有几个数字说明是几维

(3,)


In [13]:
print(a2.shape)

(2, 3)


In [15]:
print(a3.shape)

(2, 2, 3)


In [20]:
#reshape
a4=a3.reshape((2,6))
print(a4)
print(a4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [28]:
a5= a3.reshape((12,))
print(a5)
print(a5.ndim)

a5=a3.flatten()#扁平化，把数组变为一维数组

print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [29]:
count = a3.size#获取元素的个数（不管几维数组）
print(count)

12


In [31]:
itemsize = a3.itemsize#每个元素多少个字节
print(itemsize)

4


# 总结
1. 数组一般都转换为2维数组来计算
2. 通过ndarray.ndim可以看到数组的维度，ndarray.shape 可以看到数组（几行几列）
3. ndarray.reshape 注意修改前后元素个数要一样
4. ndarray.size 可以看到数组公有几个元素
5. ndarray.itemsize可以看到数组中每个元素所占内存大小，单位是字节（1个字节=8位）

In [37]:
b = np.array([
              [1,2,3],
              [4,5,6]
             ])

In [41]:
print(b)
print(b.shape)
b1 = b.reshape((3,2))
print(b1)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [42]:
c = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(c.shape)

(3, 2)


# ndarray的储存、输出方式是：先从左到右，再从上向下,并且直接通过【】来控制行和列